In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Use relative path instead of absolute path
data_file = 'ObesityDataSet_raw_and_data_sinthetic.csv'
df = pd.read_csv(data_file)

In [175]:
# Load Dataset
df = pd.read_csv(r'C:\Users\Emre\Desktop\superlig\ObesityDataSet_raw_and_data_sinthetic.csv')

Dataset Information

This dataset include data for the estimation of obesity levels in individuals from the countries of Mexico, Peru and Colombia, based on their eating habits and physical condition. The data contains 17 attributes and 2111 records, the records are labeled with the class variable NObesity (Obesity Level), that allows classification of the data using the values of Insufficient Weight, Normal Weight, Overweight Level I, Overweight Level II, Obesity Type I, Obesity Type II and Obesity Type III. 77% of the data was generated synthetically using the Weka tool and the SMOTE filter, 23% of the data was collected directly from users through a web platform.

Gender: Feature, Categorical, "Gender"

Age : Feature, Continuous, "Age"

Height: Feature, Continuous

Weight: Feature Continuous

family_history_with_overweight: Feature, Binary, " Has a family member suffered or suffers from overweight? "

FAVC : Feature, Binary, " Do you eat high caloric food frequently? "

FCVC : Feature, Integer, " Do you usually eat vegetables in your meals? "

NCP : Feature, Continuous, " How many main meals do you have daily? "

CAEC : Feature, Categorical, " Do you eat any food between meals? "

SMOKE : Feature, Binary, " Do you smoke? "

CH2O: Feature, Continuous, " How much water do you drink daily? "

SCC: Feature, Binary, " Do you monitor the calories you eat daily? "

FAF: Feature, Continuous, " How often do you have physical activity? "

TUE : Feature, Integer, " How much time do you use technological devices such as cell phone, videogames, television, computer and others? "

CALC : Feature, Categorical, " How often do you drink alcohol? "

MTRANS : Feature, Categorical, " Which transportation do you usually use? "

NObeyesdad : Target, Categorical, "Obesity level"

In [176]:
# Display Sample Data
df.sample(5)

Age  Gender    Height      Weight       CALC FAVC      FCVC  \
742   18.000000    Male  1.719827   52.289828  Sometimes  yes  1.202075   
447   19.000000    Male  1.800000   87.000000  Sometimes  yes  2.000000   
1335  18.729566    Male  1.855433  112.875283  Sometimes  yes  2.000000   
1407  21.895468  Female  1.644560   88.119139         no  yes  2.693859   
1256  18.000000    Male  1.791174  108.960600         no  yes  2.000000   

           NCP SCC SMOKE      CH2O family_history_with_overweight       FAF  \
742   3.000000  no    no  1.927976                            yes  0.023574   
447   4.000000  no    no  2.000000                            yes  2.000000   
1335  2.427137  no    no  2.574073                            yes  1.000000   
1407  1.000283  no    no  3.000000                            yes  1.201403   
1256  1.086870  no    no  2.279124                            yes  1.000000   

           TUE       CAEC                 MTRANS           NObeyesdad  
742   1.747256  Sometimes  Public_Transportation  Insufficient_Weight  
447   1.000000  Sometimes  Public_Transportation   Overweight_Level_I  
1335  2.000000  Sometimes  Public_Transportation       Obesity_Type_I  
1407  1.612432  Sometimes  Public_Transportation       Obesity_Type_I  
1256  1.609773  Sometimes  Public_Transportation       Obesity_Type_I

In [177]:
# Dataset Information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Age                             2111 non-null   float64
 1   Gender                          2111 non-null   object 
 2   Height                          2111 non-null   float64
 3   Weight                          2111 non-null   float64
 4   CALC                            2111 non-null   object 
 5   FAVC                            2111 non-null   object 
 6   FCVC                            2111 non-null   float64
 7   NCP                             2111 non-null   float64
 8   SCC                             2111 non-null   object 
 9   SMOKE                           2111 non-null   object 
 10  CH2O                            2111 non-null   float64
 11  family_history_with_overweight  2111 non-null   object 
 12  FAF                             21

In [178]:
# Statistical Summary
df.describe()

Age       Height       Weight         FCVC          NCP  \
count  2111.000000  2111.000000  2111.000000  2111.000000  2111.000000   
mean     24.312600     1.701677    86.586058     2.419043     2.685628   
std       6.345968     0.093305    26.191172     0.533927     0.778039   
min      14.000000     1.450000    39.000000     1.000000     1.000000   
25%      19.947192     1.630000    65.473343     2.000000     2.658738   
50%      22.777890     1.700499    83.000000     2.385502     3.000000   
75%      26.000000     1.768464   107.430682     3.000000     3.000000   
max      61.000000     1.980000   173.000000     3.000000     4.000000   

              CH2O          FAF          TUE  
count  2111.000000  2111.000000  2111.000000  
mean      2.008011     1.010298     0.657866  
std       0.612953     0.850592     0.608927  
min       1.000000     0.000000     0.000000  
25%       1.584812     0.124505     0.000000  
50%       2.000000     1.000000     0.625350  
75%       2.477420     1.666678     1.000000  
max       3.000000     3.000000     2.000000

In [179]:
# Display Last 5 Rows
df.tail()

Age  Gender    Height      Weight       CALC FAVC  FCVC  NCP SCC  \
2106  20.976842  Female  1.710730  131.408528  Sometimes  yes   3.0  3.0  no   
2107  21.982942  Female  1.748584  133.742943  Sometimes  yes   3.0  3.0  no   
2108  22.524036  Female  1.752206  133.689352  Sometimes  yes   3.0  3.0  no   
2109  24.361936  Female  1.739450  133.346641  Sometimes  yes   3.0  3.0  no   
2110  23.664709  Female  1.738836  133.472641  Sometimes  yes   3.0  3.0  no   

     SMOKE      CH2O family_history_with_overweight       FAF       TUE  \
2106    no  1.728139                            yes  1.676269  0.906247   
2107    no  2.005130                            yes  1.341390  0.599270   
2108    no  2.054193                            yes  1.414209  0.646288   
2109    no  2.852339                            yes  1.139107  0.586035   
2110    no  2.863513                            yes  1.026452  0.714137   

           CAEC                 MTRANS        NObeyesdad  
2106  Sometimes  Public_Transportation  Obesity_Type_III  
2107  Sometimes  Public_Transportation  Obesity_Type_III  
2108  Sometimes  Public_Transportation  Obesity_Type_III  
2109  Sometimes  Public_Transportation  Obesity_Type_III  
2110  Sometimes  Public_Transportation  Obesity_Type_III

In [180]:
# Check Missing Values
df.isna().sum()

Age                               0
Gender                            0
Height                            0
Weight                            0
CALC                              0
FAVC                              0
FCVC                              0
NCP                               0
SCC                               0
SMOKE                             0
CH2O                              0
family_history_with_overweight    0
FAF                               0
TUE                               0
CAEC                              0
MTRANS                            0
NObeyesdad                        0
dtype: int64

In [181]:
# Check Duplicate Rows
df.duplicated().sum()

np.int64(24)

In [182]:
# Remove Duplicate Rows
df.drop_duplicates(inplace=True)

In [183]:
# Dataset Info After Cleaning
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2087 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Age                             2087 non-null   float64
 1   Gender                          2087 non-null   object 
 2   Height                          2087 non-null   float64
 3   Weight                          2087 non-null   float64
 4   CALC                            2087 non-null   object 
 5   FAVC                            2087 non-null   object 
 6   FCVC                            2087 non-null   float64
 7   NCP                             2087 non-null   float64
 8   SCC                             2087 non-null   object 
 9   SMOKE                           2087 non-null   object 
 10  CH2O                            2087 non-null   float64
 11  family_history_with_overweight  2087 non-null   object 
 12  FAF                             2087 no

In [184]:
# Display Data After Cleaning
df.tail()

Age  Gender    Height      Weight       CALC FAVC  FCVC  NCP SCC  \
2106  20.976842  Female  1.710730  131.408528  Sometimes  yes   3.0  3.0  no   
2107  21.982942  Female  1.748584  133.742943  Sometimes  yes   3.0  3.0  no   
2108  22.524036  Female  1.752206  133.689352  Sometimes  yes   3.0  3.0  no   
2109  24.361936  Female  1.739450  133.346641  Sometimes  yes   3.0  3.0  no   
2110  23.664709  Female  1.738836  133.472641  Sometimes  yes   3.0  3.0  no   

     SMOKE      CH2O family_history_with_overweight       FAF       TUE  \
2106    no  1.728139                            yes  1.676269  0.906247   
2107    no  2.005130                            yes  1.341390  0.599270   
2108    no  2.054193                            yes  1.414209  0.646288   
2109    no  2.852339                            yes  1.139107  0.586035   
2110    no  2.863513                            yes  1.026452  0.714137   

           CAEC                 MTRANS        NObeyesdad  
2106  Sometimes  Public_Transportation  Obesity_Type_III  
2107  Sometimes  Public_Transportation  Obesity_Type_III  
2108  Sometimes  Public_Transportation  Obesity_Type_III  
2109  Sometimes  Public_Transportation  Obesity_Type_III  
2110  Sometimes  Public_Transportation  Obesity_Type_III

In [185]:
# Data Type Conversions and Feature Engineering
df['Age'] = df['Age'].astype(int)  # Convert Age to integer
df['Height'] = df['Height'].round(2)  # Round Height to 2 decimals
df['Weight'] = df['Weight'].round(2)  # Round Weight to 2 decimals

# Calculate BMI (Body Mass Index)
df['BMI'] = (df['Weight'] / (df['Height'] ** 2)).round(2)

In [186]:
# Display Updated Data
df.tail()

Age  Gender  Height  Weight       CALC FAVC  FCVC  NCP SCC SMOKE  \
2106   20  Female    1.71  131.41  Sometimes  yes   3.0  3.0  no    no   
2107   21  Female    1.75  133.74  Sometimes  yes   3.0  3.0  no    no   
2108   22  Female    1.75  133.69  Sometimes  yes   3.0  3.0  no    no   
2109   24  Female    1.74  133.35  Sometimes  yes   3.0  3.0  no    no   
2110   23  Female    1.74  133.47  Sometimes  yes   3.0  3.0  no    no   

          CH2O family_history_with_overweight       FAF       TUE       CAEC  \
2106  1.728139                            yes  1.676269  0.906247  Sometimes   
2107  2.005130                            yes  1.341390  0.599270  Sometimes   
2108  2.054193                            yes  1.414209  0.646288  Sometimes   
2109  2.852339                            yes  1.139107  0.586035  Sometimes   
2110  2.863513                            yes  1.026452  0.714137  Sometimes   

                     MTRANS        NObeyesdad    BMI  
2106  Public_Transportation  Obesity_Type_III  44.94  
2107  Public_Transportation  Obesity_Type_III  43.67  
2108  Public_Transportation  Obesity_Type_III  43.65  
2109  Public_Transportation  Obesity_Type_III  44.04  
2110  Public_Transportation  Obesity_Type_III  44.08

In [187]:
# Check Unique Values in Each Column
for column in df.columns:
    print(f"\n{column} column unique values:")
    print(df[column].unique())


Age column unique values:
[21 23 27 22 29 24 26 41 30 52 20 19 31 39 17 25 55 38 18 15 61 44 34 36
 32 35 40 45 33 51 56 28 16 37 14 42 50 43 46 47]

Gender column unique values:
['Female' 'Male']

Height column unique values:
[1.62 1.52 1.8  1.78 1.5  1.64 1.72 1.85 1.65 1.77 1.7  1.93 1.53 1.71
 1.69 1.6  1.75 1.68 1.58 1.79 1.56 1.67 1.66 1.81 1.82 1.55 1.61 1.63
 1.76 1.57 1.88 1.87 1.89 1.74 1.83 1.92 1.73 1.84 1.91 1.48 1.59 1.54
 1.9  1.86 1.45 1.98 1.51 1.46 1.49 1.95 1.94]

Weight column unique values:
[ 64.    56.    77.   ... 131.41 133.69 133.35]

CALC column unique values:
['no' 'Sometimes' 'Frequently' 'Always']

FAVC column unique values:
['no' 'yes']

FCVC column unique values:
[2.       3.       1.       2.450218 2.880161 2.00876  2.596579 2.591439
 2.392665 1.123939 2.027574 2.658112 2.88626  2.714447 2.750715 1.4925
 2.205439 2.059138 2.310423 2.823179 2.052932 2.596364 2.767731 2.815157
 2.737762 2.568063 2.524428 2.971574 1.0816   1.270448 1.344854 2.959658
 2.725

In [188]:
# Categorical to Numerical Mapping
mapping = {
    'Gender': {
        'Female': 0,
        'Male': 1
    },
    'CALC': {
        'no': 0,
        'Sometimes': 1,
        'Frequently': 2,
        'Always': 3
    },
    'FAVC': {
        'no': 0,
        'yes': 1,
    },
    'SCC': {
        'no': 0,
        'yes': 1,
    },
    'SMOKE': {
        'no': 0,
        'yes': 1,
    },
    'family_history_with_overweight': {
        'no': 0,
        'yes': 1
    },
    'CAEC': {
        'Sometimes': 3,
        'Frequently': 2,
        'Always': 4,
        'no': 0
    },
    'MTRANS': {
        'Public_Transportation': 0,
        'Walking': 1,
        'Automobile': 2,
        'Motorbike': 3,
        'Bike': 4
    },
    'NObeyesdad': {
        'Normal_Weight': 0,
        'Overweight_Level_I': 1,
        'Overweight_Level_II': 2,
        'Obesity_Type_I': 3,
        'Insufficient_Weight': 4,
        'Obesity_Type_II': 5,
        'Obesity_Type_III': 6
    }
}

# Apply Mapping to DataFrame
df = df.replace(mapping)

In [189]:
# Display Final Dataset
df

Age  Gender  Height  Weight  CALC  FAVC  FCVC  NCP  SCC  SMOKE  \
0      21       0    1.62   64.00     0     0   2.0  3.0    0      0   
1      21       0    1.52   56.00     1     0   3.0  3.0    1      1   
2      23       1    1.80   77.00     2     0   2.0  3.0    0      0   
3      27       1    1.80   87.00     2     0   3.0  3.0    0      0   
4      22       1    1.78   89.80     1     0   2.0  1.0    0      0   
...   ...     ...     ...     ...   ...   ...   ...  ...  ...    ...   
2106   20       0    1.71  131.41     1     1   3.0  3.0    0      0   
2107   21       0    1.75  133.74     1     1   3.0  3.0    0      0   
2108   22       0    1.75  133.69     1     1   3.0  3.0    0      0   
2109   24       0    1.74  133.35     1     1   3.0  3.0    0      0   
2110   23       0    1.74  133.47     1     1   3.0  3.0    0      0   

          CH2O  family_history_with_overweight       FAF       TUE  CAEC  \
0     2.000000                               1  0.000000  1.000000     3   
1     3.000000                               1  3.000000  0.000000     3   
2     2.000000                               1  2.000000  1.000000     3   
3     2.000000                               0  2.000000  0.000000     3   
4     2.000000                               0  0.000000  0.000000     3   
...        ...                             ...       ...       ...   ...   
2106  1.728139                               1  1.676269  0.906247     3   
2107  2.005130                               1  1.341390  0.599270     3   
2108  2.054193                               1  1.414209  0.646288     3   
2109  2.852339                               1  1.139107  0.586035     3   
2110  2.863513                               1  1.026452  0.714137     3   

      MTRANS  NObeyesdad    BMI  
0          0           0  24.39  
1          0           0  24.24  
2          0           0  23.77  
3          1           1  26.85  
4          0           2  28.34  
...      ...         ...    ...  
2106       0           6  44.94  
2107       0           6  43.67  
2108       0           6  43.65  
2109       0           6  44.04  
2110       0           6  44.08  

[2087 rows x 18 columns]

In [190]:
# Final Dataset Information
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2087 entries, 0 to 2110
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Age                             2087 non-null   int64  
 1   Gender                          2087 non-null   int64  
 2   Height                          2087 non-null   float64
 3   Weight                          2087 non-null   float64
 4   CALC                            2087 non-null   int64  
 5   FAVC                            2087 non-null   int64  
 6   FCVC                            2087 non-null   float64
 7   NCP                             2087 non-null   float64
 8   SCC                             2087 non-null   int64  
 9   SMOKE                           2087 non-null   int64  
 10  CH2O                            2087 non-null   float64
 11  family_history_with_overweight  2087 non-null   int64  
 12  FAF                             2087 no

In [191]:
# Check Column Ranges for Scaling Decision
print("Column Min-Max Values:")
print("-" * 50)
for col in df.columns:
    if df[col].dtype in ['float64', 'int64']:
        print(f"{col:30} | Min: {df[col].min():8.2f} | Max: {df[col].max():8.2f} | Range: {df[col].max() - df[col].min():8.2f}")

Column Min-Max Values:
--------------------------------------------------
Age                            | Min:    14.00 | Max:    61.00 | Range:    47.00
Gender                         | Min:     0.00 | Max:     1.00 | Range:     1.00
Height                         | Min:     1.45 | Max:     1.98 | Range:     0.53
Weight                         | Min:    39.00 | Max:   173.00 | Range:   134.00
CALC                           | Min:     0.00 | Max:     3.00 | Range:     3.00
FAVC                           | Min:     0.00 | Max:     1.00 | Range:     1.00
FCVC                           | Min:     1.00 | Max:     3.00 | Range:     2.00
NCP                            | Min:     1.00 | Max:     4.00 | Range:     3.00
SCC                            | Min:     0.00 | Max:     1.00 | Range:     1.00
SMOKE                          | Min:     0.00 | Max:     1.00 | Range:     1.00
CH2O                           | Min:     1.00 | Max:     3.00 | Range:     2.00
family_history_with_overweight | Mi

In [192]:
# Feature Scaling with StandardScaler
from sklearn.preprocessing import StandardScaler

# Separate Features (X) and Target (y)
X = df.drop('NObeyesdad', axis=1)  # Features (input)
y = df['NObeyesdad']  # Target (output)

print("Features (X) columns:")
print(X.columns.tolist())
print(f"\nFeatures shape: {X.shape}")
print(f"Target shape: {y.shape}")

# Apply StandardScaler to Features Only
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Convert Scaled Data to DataFrame
X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns)

Features (X) columns:
['Age', 'Gender', 'Height', 'Weight', 'CALC', 'FAVC', 'FCVC', 'NCP', 'SCC', 'SMOKE', 'CH2O', 'family_history_with_overweight', 'FAF', 'TUE', 'CAEC', 'MTRANS', 'BMI']

Features shape: (2087, 17)
Target shape: (2087,)


In [193]:
# Machine Learning Pipeline Setup
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import warnings
warnings.filterwarnings('ignore')

# Train/Test Split (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled_df, y, test_size=0.2, random_state=42, stratify=y
)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

# Target Distribution in Training Set
print(f"\nTarget Distribution (y_train):")
print(y_train.value_counts().sort_index())

X_train shape: (1669, 17)
X_test shape: (418, 17)
y_train shape: (1669,)
y_test shape: (418,)

Target Distribution (y_train):
NObeyesdad
0    225
1    221
2    232
3    281
4    214
5    237
6    259
Name: count, dtype: int64
NObeyesdad
0    225
1    221
2    232
3    281
4    214
5    237
6    259
Name: count, dtype: int64


In [194]:
# Model Comparison and Training
models = {
    'Random Forest': RandomForestClassifier(n_estimators=100, random_state=42),
    'Logistic Regression': LogisticRegression(random_state=42, max_iter=1000),
    'SVM': SVC(random_state=42),
    'KNN': KNeighborsClassifier(n_neighbors=5)
}

# Store Model Performance
results = {}

print("🚀 Model Training Started...")
print("=" * 50)

for name, model in models.items():
    # Train Model
    model.fit(X_train, y_train)
    
    # Make Predictions
    y_pred = model.predict(X_test)
    
    # Calculate Accuracy
    accuracy = accuracy_score(y_test, y_pred)
    results[name] = accuracy
    
    print(f"{name:20} | Accuracy: {accuracy:.4f} ({accuracy*100:.2f}%)")

print("=" * 50)
print(f"🏆 Best Model: {max(results, key=results.get)} - Accuracy: {max(results.values()):.4f}")

🚀 Model Training Started...
Random Forest        | Accuracy: 0.9928 (99.28%)
Logistic Regression  | Accuracy: 0.9115 (91.15%)
SVM                  | Accuracy: 0.9234 (92.34%)
KNN                  | Accuracy: 0.8301 (83.01%)
🏆 Best Model: Random Forest - Accuracy: 0.9928
Random Forest        | Accuracy: 0.9928 (99.28%)
Logistic Regression  | Accuracy: 0.9115 (91.15%)
SVM                  | Accuracy: 0.9234 (92.34%)
KNN                  | Accuracy: 0.8301 (83.01%)
🏆 Best Model: Random Forest - Accuracy: 0.9928


In [195]:
# Detailed Analysis of Best Model
best_model_name = max(results, key=results.get)
best_model = models[best_model_name]

# Make Predictions with Best Model
y_pred_best = best_model.predict(X_test)

print(f"🔍 {best_model_name} - Detailed Analysis")
print("=" * 50)

# Classification Report
print("\n📊 Classification Report:")
print(classification_report(y_test, y_pred_best))

# Confusion Matrix
print("\n🎯 Confusion Matrix:")
cm = confusion_matrix(y_test, y_pred_best)
print(cm)

# Obesity Class Labels
obesity_classes = {
    0: 'Normal_Weight',
    1: 'Overweight_Level_I', 
    2: 'Overweight_Level_II',
    3: 'Obesity_Type_I',
    4: 'Insufficient_Weight',
    5: 'Obesity_Type_II',
    6: 'Obesity_Type_III'
}

print("\n🏷️ Class Labels:")
for key, value in obesity_classes.items():
    print(f"{key}: {value}")

🔍 Random Forest - Detailed Analysis

📊 Classification Report:
              precision    recall  f1-score   support

           0       0.97      1.00      0.98        57
           1       1.00      0.96      0.98        55
           2       1.00      1.00      1.00        58
           3       1.00      1.00      1.00        70
           4       1.00      1.00      1.00        53
           5       0.98      1.00      0.99        60
           6       1.00      0.98      0.99        65

    accuracy                           0.99       418
   macro avg       0.99      0.99      0.99       418
weighted avg       0.99      0.99      0.99       418


🎯 Confusion Matrix:
[[57  0  0  0  0  0  0]
 [ 2 53  0  0  0  0  0]
 [ 0  0 58  0  0  0  0]
 [ 0  0  0 70  0  0  0]
 [ 0  0  0  0 53  0  0]
 [ 0  0  0  0  0 60  0]
 [ 0  0  0  0  0  1 64]]

🏷️ Class Labels:
0: Normal_Weight
1: Overweight_Level_I
2: Overweight_Level_II
3: Obesity_Type_I
4: Insufficient_Weight
5: Obesity_Type_II
6: Obesity_

In [204]:
# Fixed Obesity Prediction Function with Random Forest
def predict_obesity_level(gender, age, height, weight, family_history, favc, fcvc, ncp, caec, smoke, ch2o, scc, faf, tue, calc, mtrans):
    """
    Predicts obesity level based on personal characteristics
    
    Parameters:
    - gender: 'Male' or 'Female'
    - age: Age in years (int)
    - height: Height in meters (float, e.g., 1.70)
    - weight: Weight in kg (float, e.g., 65.5)
    - family_history: 'yes' or 'no'
    - favc: 'yes' or 'no' (Do you eat high caloric food frequently?)
    - fcvc: 1-3 (Do you usually eat vegetables in your meals?)
    - ncp: 1-4 (How many main meals do you have daily?)
    - caec: 'no', 'Sometimes', 'Frequently', 'Always' (Do you eat food between meals?)
    - smoke: 'yes' or 'no'
    - ch2o: 1-3 (How much water do you drink daily?)
    - scc: 'yes' or 'no' (Do you monitor calories?)
    - faf: 0-3 (How often do you have physical activity?)
    - tue: 0-2 (Time using technology devices?)
    - calc: 'no', 'Sometimes', 'Frequently', 'Always' (How often do you drink alcohol?)
    - mtrans: 'Public_Transportation', 'Walking', 'Automobile', 'Motorbike', 'Bike'
    
    Returns:
    - Predicted obesity level and probability
    """
    
    # Calculate BMI
    bmi = round(weight / (height ** 2), 2)
    
    # Create input data in the EXACT order the model expects
    # Order: ['Age', 'Gender', 'Height', 'Weight', 'CALC', 'FAVC', 'FCVC', 'NCP', 'SCC', 'SMOKE', 'CH2O', 'family_history_with_overweight', 'FAF', 'TUE', 'CAEC', 'MTRANS', 'BMI']
    input_data = {
        'Age': age,
        'Gender': 1 if gender.lower() == 'male' else 0,
        'Height': height,
        'Weight': weight,
        'CALC': {'no': 0, 'sometimes': 1, 'frequently': 2, 'always': 3}[calc.lower()],
        'FAVC': 1 if favc.lower() == 'yes' else 0,
        'FCVC': fcvc,
        'NCP': ncp,
        'SCC': 1 if scc.lower() == 'yes' else 0,
        'SMOKE': 1 if smoke.lower() == 'yes' else 0,
        'CH2O': ch2o,
        'family_history_with_overweight': 1 if family_history.lower() == 'yes' else 0,
        'FAF': faf,
        'TUE': tue,
        'CAEC': {'no': 0, 'sometimes': 3, 'frequently': 2, 'always': 4}[caec.lower()],
        'MTRANS': {'public_transportation': 0, 'walking': 1, 'automobile': 2, 'motorbike': 3, 'bike': 4}[mtrans.lower()],
        'BMI': bmi
    }
    
    # Convert to DataFrame with correct column order
    input_df = pd.DataFrame([input_data])
    
    # Ensure the column order matches exactly what the model expects
    input_df = input_df[X.columns]
    
    # Scale the input data
    input_scaled = scaler.transform(input_df)
    
    # Make prediction
    prediction = best_model.predict(input_scaled)[0]
    prediction_proba = best_model.predict_proba(input_scaled)[0]
    
    # Convert prediction to class name
    obesity_classes = {
        0: 'Normal Weight',
        1: 'Overweight Level I', 
        2: 'Overweight Level II',
        3: 'Obesity Type I',
        4: 'Insufficient Weight',
        5: 'Obesity Type II',
        6: 'Obesity Type III'
    }
    
    predicted_class = obesity_classes[prediction]
    confidence = prediction_proba[prediction] * 100
    
    print(f"🎯 Prediction Results:")
    print(f"BMI: {bmi}")
    print(f"Predicted Obesity Level: {predicted_class}")
    print(f"Confidence: {confidence:.1f}%")
    print(f"\nAll Class Probabilities:")
    for i, prob in enumerate(prediction_proba):
        print(f"  {obesity_classes[i]}: {prob*100:.1f}%")
    
    return predicted_class, confidence

print("✅ Fixed Obesity Prediction Function Ready!")
print("✅ Feature order now matches the trained model!")

✅ Fixed Obesity Prediction Function Ready!
✅ Feature order now matches the trained model!


In [208]:
# Save Model and Scaler for Web API
import pickle
import joblib

# Save the trained model
joblib.dump(best_model, 'obesity_model.pkl')
joblib.dump(scaler, 'scaler.pkl')

print("✅ Model and Scaler saved!")
print("- obesity_model.pkl: Trained Random Forest model")
print("- scaler.pkl: Fitted StandardScaler")

✅ Model and Scaler saved!
- obesity_model.pkl: Trained Random Forest model
- scaler.pkl: Fitted StandardScaler
